/* SPDX-License-Identifier: GPL-2.0+ */
/*
 *
 */

#include <sysinfo.h>

enum sysinfo_id_iot2050 {
	BOARD_MLFB = SYSINFO_ID_SMBIOS_SYSTEM_VERSION,
	BOARD_NAME,
	BOARD_SERIAL,
	BOARD_UUID,
	BOARD_A5E,
	BOARD_SEBOOT_VER,
	BOARD_MAC_ADDR_CNT,
	BOARD_MAC_ADDR_START,
	BOARD_MAC_ADDR_1 = BOARD_MAC_ADDR_START,
	BOARD_MAC_ADDR_2,
	BOARD_MAC_ADDR_3,
	BOARD_MAC_ADDR_4,
	BOARD_MAC_ADDR_5,
	BOARD_MAC_ADDR_6,
	BOARD_MAC_ADDR_7,
	BOARD_MAC_ADDR_8,
	BOARD_DDR_SIZE,
};
